### ISSUE TITLE
Should beta.glm have an intercept equal to 0?

### ISSUE THREAD

**Issue by KZARCA** [jeff-hughes/reghelper#13]
Hi, 
Consider the following regression model:
```
mod <- glm(formula = sex ~ age + nodes, family = binomial, data = survival::colon)
beta(mod)
```
I get:
```
Coefficients:
            Estimate Std. Error z value Pr(>|z|)  
(Intercept)  0.09012    0.04692   1.921   0.0548 .
age.z        0.03943    0.04713   0.837   0.4028  
nodes.z     -0.03457    0.04713  -0.734   0.4632  
```
I'm not sure what is the expected output, but I was wondering if the intercept in the beta.glm should be equal to 0. What is your view on this point?
Best

**Comment by jeff-hughes** [comment]
Hi @KZARCA,
The default behaviour for `beta.glm()` is that it does not standardize the outcome variable. This is essentially because in most cases, these variables are nominal or ordinal, and standardizing may not be appropriate (or at least results in a model that is difficult to interpret).

If you wish to override this, you can run `beta(mod, y=TRUE)` to force it to standardize the outcome. Or alternately, you can use `scale()` to standardize the outcome first, then use that in the model.

**Comment by KZARCA** [comment]
Thanks!
